name: PHP Composer

on:
  push:
    branches: [ "main", "develop", "release/*", "feature/*", "hotfix/*" ] 
  pull_request:
    branches: [ "main", "develop", "release/*", "feature/*", "hotfix/*" ]  
permissions:
  contents: read 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, json
          coverage: none

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      
    - name: Run tests (for feature and hotfix)
      run: |
        vendor/bin/phpunit --configuration phpunit.xml  # Kiểm thử các tính năng và hotfix

    
    - name: Deploy to Staging (for feature branches)
      if: startsWith(github.ref, 'refs/heads/feature/')
      run: |
        echo "Deploying to staging environment for feature branch..."
        # Deploy lên môi trường dev, staging hay server thử nghiệm của bạn
        # Thí dụ: Dùng SSH hoặc các công cụ deploy tự động

    
    - name: Deploy to Production (only from main and release branches)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
      run: |
        echo "Deploying to production environment..."
        # Các bước deploy lên môi trường production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./php_program/php_program


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

